# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [7]:
my_1D = np.array([1,2,3])
print(my_1D)

[1 2 3]


In [8]:
my_2D = np.array([[1,2,3], [4,5,6]])
print(my_2D)

[[1 2 3]
 [4 5 6]]


In [9]:
my_3D = np.array([[[4,5,6], [1,2,3]], [[7,8,9], [10,11,12]]])
print(my_3D)

[[[ 4  5  6]
  [ 1  2  3]]

 [[ 7  8  9]
  [10 11 12]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [11]:
#returns number of dimensions in array
print(my_3D.ndim)
#returns a tuple of array dimensions
print(my_3D.shape)
#returns the number of elements in the array 
print(my_3D.size)
#returns the data type of the array's elemetnts. here is integers of 32bit 
print(my_3D.dtype)
#returns the length of one array element in bytes
print(my_3D.itemsize)
#returns a Python buffer object pointing to the start of the array 
print(my_3D.data)
#returns the number of  bytes occupied by the array 
print(my_3D.nbytes)

3
(2, 2, 3)
12
int32
4
48


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [30]:
#Return a new array of given shape and type, filled with ones 
my_ones = np.ones(5, dtype = int)
print(my_ones)
#Return a new array of given shape and type, filled with zeros 
my_zeros = np.zeros(7, dtype = int)
print(my_zeros)
#Returns a new array of given shape and type, without initializing entries
my_empty = np.empty([5,6])
print(my_empty)
#Return a new array of given shape and type, filled with fill_value
my_full = np.full([4,7], 8)
print(my_full)
#Return evenly spaced values within a given interval
my_arange = np.arange(5)
print(my_arange)
#Return evenly spaced numbers over a specified interval, 
#Returns num evenly spaced samples, calculated over the interval [start, stop]
my_linspace = np.linspace(5,9, num = 8)
print(my_linspace)
#Can be used to return a single random value or an array of random values between 0 and 1
my_random = np.random.random_sample((2,3)) -4
print(my_random)


[1 1 1 1 1]
[0 0 0 0 0 0 0]
[[1.45313759e-311 9.58487353e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000 5.02034658e+175]
 [4.43201830e+175 2.89892167e-057 6.00103273e-066 5.70112961e-038
  1.47763641e+248 1.16096346e-028]
 [7.69165785e+218 1.35617292e+248 1.13952701e-071 5.40662172e-066
  3.38209932e-061 4.90844587e-062]
 [4.30530275e-096 6.32299154e+233 6.48224638e+170 5.22411352e+257
  5.74020278e+180 8.37174974e-144]
 [1.41529402e+161 6.00736899e-067 4.52743858e+097 9.75035690e-072
  3.24724168e+126 6.79764374e-310]]
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]
[0 1 2 3 4]
[5.         5.57142857 6.14285714 6.71428571 7.28571429 7.85714286
 8.42857143 9.        ]
[[-3.28102741 -3.32133584 -3.98299359]
 [-3.99277108 -3.64713643 -3.60762495]]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [34]:
a_my_array = np.ones((3,4), dtype = int)
b_my_array = np.random.random((3,4))
print(a_my_array)
print(b_my_array)
a_my_array + b_my_array

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0.77447031 0.24627532 0.3672069  0.2566148 ]
 [0.08389736 0.71580696 0.3449881  0.17775234]
 [0.38409619 0.85501618 0.06984023 0.96027974]]


array([[0.22552969, 0.75372468, 0.6327931 , 0.7433852 ],
       [0.91610264, 0.28419304, 0.6550119 , 0.82224766],
       [0.61590381, 0.14498382, 0.93015977, 0.03972026]])

In [35]:
a_my_array - b_my_array

array([[0.22552969, 0.75372468, 0.6327931 , 0.7433852 ],
       [0.91610264, 0.28419304, 0.6550119 , 0.82224766],
       [0.61590381, 0.14498382, 0.93015977, 0.03972026]])

In [36]:
a_my_array * b_my_array

array([[0.77447031, 0.24627532, 0.3672069 , 0.2566148 ],
       [0.08389736, 0.71580696, 0.3449881 , 0.17775234],
       [0.38409619, 0.85501618, 0.06984023, 0.96027974]])

In [37]:
incompatible_1 = np.ones((5,7))
inocmpatible_2 = np.array([3,4])

inocmpatible_2 * incompatible_1

ValueError: operands could not be broadcast together with shapes (2,) (5,7) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [46]:
array_1 = np.ones((4,5))
print(array_1)
array_2 = np.full((4,5),8)
print(array_2)
array_3 = np.array([[1,2,3], [4,5,6]])
print(array_3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[[1 2 3]
 [4 5 6]]


In [57]:
#Sum of array elements over a given axis
array_sum = np.sum(array_1, 0)
print( array_sum)
#Element-wise minimum of array elements
array_min = np.minimum(array_1, array_2)
print(array_min)
#Element-wise maximum of array elements
array_max = np.maximum(array_1, array_2)
print(array_max)
#returns the cummulative sum of the elements along a given axes
cumsum = np.cumsum(array_2,0)
print(cumsum)
#compute the arithmetic mean along the specified axis
array_mean = np.mean(array_3, 1)
print(array_mean)
#return Pearson product-moment correlation coefficients between two 1D arrays or one 2D array
array_corrcoef = np.corrcoef(array_2, array_1)
print(array_corrcoef)
# compute the standard deviation along the specified axis
stddev = np.std(array_3, 1)
print(stddev)
#compute the variance along the specified axis
array_var = np.var(array_3, 1)
print(array_var)

[4. 4. 4. 4. 4.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]]
[[ 8  8  8  8  8]
 [16 16 16 16 16]
 [24 24 24 24 24]
 [32 32 32 32 32]]
[2. 5.]
[[nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]]
[0.81649658 0.81649658]
[0.66666667 0.66666667]


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [64]:
logic_a = [True, True, True, False, True]
logic_b = [False, False, True, True, False]
#computes the element-wise truth value of two arrays using AND
boolean_and = np.logical_and(logic_a, logic_b)
print(boolean_and)
#computes the element-wise truth value of two arrays using OR
boolean_or = np.logical_or(logic_a, logic_b)
print(boolean_or)
# computes the element-wise truth value of two arrays using NOT
boolean_not = np.logical_not(logic_a, 0)
print(boolean_not)


[False False  True False False]
[ True  True  True  True  True]


TypeError: return arrays must be of ArrayType